name: untitled4
description: "A new Flutter project with Firebase integration."
publish_to: 'none'

version: 1.0.0+1  # You can define the version number

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase core package
  firebase_core: ^2.17.0

  # Firebase Authentication (for user authentication)
  firebase_auth: ^4.5.0

  # Cloud Firestore (for storing messages and other data)
  cloud_firestore: ^4.5.0

  # Firebase Storage (if you want to store images, etc.)
  firebase_storage: ^11.5.0

  # Firebase Messaging (for push notifications)
  firebase_messaging:

  # Firebase Realtime Database (if you prefer real-time database over Firestore)
  firebase_database: ^10.5.0

  # cupertino_icons for iOS style icons
  cupertino_icons: ^1.0.8

  # Provider for state management (use version 6.1.2 for compatibility)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - images/message.jpg
    - images/logo.png
